[project]
name = "hackathon-gmi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=3.5.1",
    "lancedb>=0.22.0",
    "pillow>=11.2.1",
    "requests>=2.32.3",
    "streamlit",
    "pandas"
]
